
*   MARYANGEL LOOR GILER
*   OCTAVO NIVEL



In [1]:
# 1. Import numpy as np and see the version
import numpy as np

print(np.__version__)
pass

1.22.4


In [3]:
# 2. Create a 1D array of numbers from 0 to 9

array_1d=np.array([0,1,2,3,4,5,6,7,8,9])

print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# 3. Create a 3×3 numpy array of all True’s

array_2d=np.ones((3,3), dtype=bool)

print(array_2d)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [6]:
# 4. Extract all odd numbers from arr

arr=[0,1,2,3,4,5,6,7,8,9]
odd_numbers={num for num in arr if num %2!=0}

print(odd_numbers)

{1, 3, 5, 7, 9}


In [7]:
# 5. Replace all odd numbers in arr with -1

arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr %2!=0]=-1

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
#  6. Convert a 1D array to a 2D array with 2 rows

arr_1d=np.array([0,1,2,3,4,5,6,7,8,9])
arr_2d=arr_1d.reshape(2, -1)

print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
#  7. Stack arrays a and b vertically

a=np.array([0,1,2])
b=np.array([3,4,5])
result=np.vstack((a,b))

print(result)

[[0 1 2]
 [3 4 5]]


In [10]:
#  8. Stack the arrays a and b horizontally.

a=np.array([0,1,2])
b=np.array([3,4,5])
result=np.hstack((a,b))

print(result)

[0 1 2 3 4 5]


In [14]:
#  9. Get all items between 5 and 10 from a.

a=np.array([1,3,5,7,9,11,13])
result=a[(a>=5)&(a<=10)]

print(result)

[5 7 9]


In [17]:
#  10. How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

def pair_max(a,b):
  return np.maximum(a,b)

a=np.array([5, 7, 9, 8, 6, 4, 5])
b=np.array([6, 3, 4, 8, 9, 7, 1])
result=pair_max(a,b)

print(result)

[6 7 9 8 9 7 5]


In [18]:
#  11. Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]

arr=np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])
arr[:, [0,1]]=arr[:, [1,0]]

print(arr)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [20]:
#  12. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

arr=np.random.uniform(5,10, size=(5,3))

print(arr)

[[7.42020377 5.11654329 5.48349924]
 [6.51032503 7.9429925  6.09813226]
 [8.71855902 8.91456054 8.55238885]
 [7.51416713 5.19676379 9.38458064]
 [7.41583312 7.57806836 5.33925364]]
